### ISSUE TITLE
upgrade directly from 18 to 18.2 (?)

### ISSUE THREAD

**Issue by awy1076** [linuxmint/mint-upgrade-info#2]
Some people miss the possibility to upgrade directly from 18 to 18.2 as announced in http://blog.linuxmint.com/?p=3306 .
Or if I have misunderstood this please apologise the inconvenience.

```
~ $ grep TITLE /etc/linuxmint/info
GRUB_TITLE=Linux Mint 18 Cinnamon 64-bit
~ $ dpkg-query -W -f='${Version}\n' mint-upgrade-info
1.0.8
~ $ grep _name /usr/share//mint-upgrade-info/sarah/info 
target_name = "Linux Mint 18.1 Serena"
~ $ 
```

**Comment by clefebvre** [comment]
Sorry about this. Fixed in 1.0.9.
